### ISSUE TITLE
the 1vs1 custom change script doesn't compile on current version of 3.3.5 TC

### ISSUE THREAD

**Issue by urwifemykids** [TrinityCore/TrinityCoreCustomChanges#145]
Title says it all

**Comment by Aokromes** [comment]
pls paste compilation error.

**Comment by urwifemykids** [comment]
Gravidade	Código	Descrição	Projeto	Arquivo	Linha	Estado de Supressão	Detalhes
Erro (ativo)	E0167	argumento do tipo "BattlegroundTypeId" é incompatível com parâmetro do tipo "const PvPDifficultyEntry *"	scripts	C:\Users\User\Desktop\Infectious master2\ThunderTCSource\src\server\scripts\Custom\npc_arena1v1.cpp	120		
Erro (ativo)	E0135	classe "BattlegroundMgr" não possui membro "BuildBattlegroundStatusPacket"	scripts	C:\Users\User\Desktop\Infectious master2\ThunderTCSource\src\server\scripts\Custom\npc_arena1v1.cpp	126		
Erro (ativo)	E0165	muito poucos argumentos na chamada da função	scripts	C:\Users\User\Desktop\Infectious master2\ThunderTCSource\src\server\scripts\Custom\npc_arena1v1.cpp	83		
Erro (ativo)	E0140	muitos argumentos na chamada da função	scripts	C:\Users\User\Desktop\Infectious master2\ThunderTCSource\src\server\scripts\Custom\npc_arena1v1.cpp	120		
Erro (ativo)	E0140	muitos argumentos na chamada da função	scripts	C:\Users\User\Desktop\Infectious master2\ThunderTCSource\src\server\scripts\Custom\npc_arena1v1.cpp	121		
Erro (ativo)	E0140	muitos argumentos na chamada da função	scripts	C:\Users\User\Desktop\Infectious master2\ThunderTCSource\src\server\scripts\Custom\npc_arena1v1.cpp	129		
Erro (ativo)	E0415	não há construtor adequado para converter "uint8" (aka "unsigned char") para "BattlegroundQueueTypeId"	scripts	C:\Users\User\Desktop\Infectious master2\ThunderTCSource\src\server\scripts\Custom\npc_arena1v1.cpp	129		
Erro (ativo)	E0020	o identificador "BATTLEGROUND_QUEUE_5v5" não está definido	scripts	C:\Users\User\Desktop\Infectious master2\ThunderTCSource\src\server\scripts\Custom\npc_arena1v1.cpp	195		
Erro (ativo)	E0434	uma referência do tipo "WorldPackets::Battleground::BattlefieldPort &" (não qualificada como constante) não pode ser inicializada com um valor do tipo "WorldPacket"	scripts	C:\Users\User\Desktop\Infectious master2\ThunderTCSource\src\server\scripts\Custom\npc_arena1v1.cpp	268
